---
ID: "49a4d55c-a3bd-447e-8845-36f9aaee4f06"
Parent: "8f099dc8-47fa-4e32-9904-2d35a86e82c0"
Template: "8f099dc8-47fa-4e32-9904-2d35a86e82c0"
Path: /sitecore/templates/Project/Sugcon2024/Basic Components/Rendering Parameters/Event/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
