name: CI-CD - SUGCON 24
on: 
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - .github/workflows/CI-CD_SUGCON_24.yml
      - .github/workflows/build_NextJs.yml
      - .github/workflows/deploy_vercel.yml
      - 'src/Project/Sugcon2024/Sugcon/**'
  pull_request:
    branches: [ main ]
    paths:
      - .github/workflows/CI-CD_SUGCON_24.yml
      - .github/workflows/build_NextJs.yml
      - .github/workflows/deploy_vercel.yml
      - 'src/Project/Sugcon2024/Sugcon/**'

jobs:

  build-sugcon24-site:
    if: github.ref != 'refs/heads/main'
    uses: ./.github/workflows/build_NextJs.yml
    with:
      workingDirectory: ./src/Project/Sugcon2024/Sugcon

  deploy-sugcon24-site:
    uses: ./.github/workflows/deploy_vercel.yml
    needs: build-sugcon24-site
    if: always() && 
        (github.repository_owner == 'Sitecore' && ((github.event.pull_request.head.repo.full_name == github.repository) || (github.event_name == 'push'))) &&
        needs.build-eu-site.result != 'failure' &&
        needs.build-eu-site.result != 'cancelled'
    secrets:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_SUGCON_24_PROJECT_ID }}